--[[
    Built-in map of DJ FiveM resources. Actions are allowlisted: the tablet
    never runs a free-form command string from NUI.
]]

Catalog = {
    {
        id = 'scriptmanager',
        resource = 'djfivem-scriptmanager',
        label = 'Script Manager',
        tag = 'Core',
        category = 'system',
        icon = 'tablet',
        description = 'This admin tablet. Resource control for itself is blocked.',
        locked = true,
        actions = {},
    },
    {
        id = 'jg-mechanic',
        resource = 'jg-mechanic',
        alts = { 'jg-mechanics' },
        label = 'JG Mechanic',
        tag = 'The 305',
        category = 'vehicles',
        icon = 'wrench',
        featured = true,
        description = 'Mechanic tablet, shop admin, and admin vehicle repair.',
        actions = {
            { id = 'tablet', label = 'Open mechanic tablet', hint = '/tablet', command = 'tablet' },
            { id = 'admin', label = 'Mechanic admin', hint = '/mechanicadmin', command = 'mechanicadmin' },
            { id = 'vfix', label = 'Fix current vehicle', hint = '/vfix', command = 'vfix' },
        },
    },
    {
        id = 'jg-garages',
        resource = 'jg-advancedgarages',
        alts = { 'jg-garages', 'jg-advanced-garages' },
        label = 'JG Garages',
        tag = 'The 305',
        category = 'vehicles',
        icon = 'car',
        featured = true,
        description = 'Impound, plates, job/gang garages, and owned-vehicle admin tools.',
        actions = {
            { id = 'impound', label = 'Impound current vehicle', hint = '/iv', command = 'iv' },
            { id = 'vplate', label = 'Change vehicle plate', hint = '/vplate', command = 'vplate' },
            { id = 'admincar', label = 'Add current vehicle to garage', hint = '/admincar', command = 'admincar' },
            { id = 'private', label = 'Private garage creator', hint = '/privategarages', command = 'privategarages' },
            { id = 'dvdb', label = 'Delete owned vehicle (DB)', hint = '/dvdb', command = 'dvdb' },
            {
                id = 'vreturn',
                label = 'Return left-out vehicle',
                hint = '/vreturn [plate]',
                command = 'vreturn {plate}',
                fields = {
                    { name = 'plate', type = 'plate', label = 'Plate' },
                },
            },
            {
                id = 'setjob',
                label = 'Move to job garage',
                hint = '/setjobvehicle [job] [grade]',
                command = 'setjobvehicle {job} {grade}',
                fields = {
                    { name = 'job', type = 'text', label = 'Job name', max = 32 },
                    { name = 'grade', type = 'number', label = 'Min grade', min = 0, max = 100, default = 0 },
                },
            },
            {
                id = 'removejob',
                label = 'Remove from job garage',
                hint = '/removejobvehicle [id]',
                command = 'removejobvehicle {player}',
                fields = {
                    { name = 'player', type = 'player', label = 'New owner' },
                },
            },
            {
                id = 'setgang',
                label = 'Move to gang garage',
                hint = '/setgangvehicle [gang] [grade]',
                command = 'setgangvehicle {gang} {grade}',
                fields = {
                    { name = 'gang', type = 'text', label = 'Gang name', max = 32 },
                    { name = 'grade', type = 'number', label = 'Min grade', min = 0, max = 100, default = 0 },
                },
            },
            {
                id = 'removegang',
                label = 'Remove from gang garage',
                hint = '/removegangvehicle [id]',
                command = 'removegangvehicle {player}',
                fields = {
                    { name = 'player', type = 'player', label = 'New owner' },
                },
            },
        },
    },
    {
        id = 'jg-dealerships',
        resource = 'jg-dealerships',
        alts = { 'jg-dealership', 'jg-advanceddealerships' },
        label = 'JG Dealerships',
        tag = 'The 305',
        category = 'vehicles',
        icon = 'key',
        featured = true,
        description = 'In-game dealer admin, stock, locations, and finance tools.',
        actions = {
            { id = 'admin', label = 'Open dealer admin', hint = '/dealeradmin', command = 'dealeradmin' },
            { id = 'directsale', label = 'Direct sale', hint = '/directsale', command = 'directsale' },
            { id = 'finance', label = 'Open my finance', hint = '/myfinance', command = 'myfinance' },
        },
    },
    {
        id = 'djbooth',
        resource = 'djbooth',
        label = 'DJ Booth',
        tag = 'Lumina',
        category = 'entertainment',
        icon = 'music',
        description = 'Booth placement, YouTube playback, playlists, and portable speakers.',
        actions = {
            { id = 'admin', label = 'Open booth admin', hint = '/djadmin', command = 'djadmin' },
            { id = 'open', label = 'Open nearest booth', hint = '/dj', command = 'dj' },
            { id = 'give_tripod', label = 'Give tripod speaker', hint = '/givespeaker lumina_speaker_tripod', command = 'givespeaker lumina_speaker_tripod' },
            { id = 'give_big', label = 'Give big speaker', hint = '/givespeaker lumina_speaker_big', command = 'givespeaker lumina_speaker_big' },
            { id = 'give_hand', label = 'Give handheld speaker', hint = '/givespeaker lumina_speaker_handheld', command = 'givespeaker lumina_speaker_handheld' },
            { id = 'place', label = 'Place a speaker', hint = '/placespeaker', command = 'placespeaker lumina_speaker_tripod' },
        },
    },
    {
        id = 'donator',
        resource = 'dj-donator',
        label = 'Donator Store',
        tag = 'Rebel Coins',
        category = 'economy',
        icon = 'store',
        description = 'Donator catalog, coin economy, vehicles, pets, and listings.',
        actions = {
            { id = 'open', label = 'Open donator store', hint = '/donator', command = 'donator' },
            {
                id = 'givecoins',
                label = 'Give coins',
                hint = '/givecoins [id] [amount]',
                command = 'givecoins {player} {amount}',
                fields = {
                    { name = 'player', type = 'player', label = 'Player' },
                    { name = 'amount', type = 'number', label = 'Amount', min = 1, max = 1000000, default = 100 },
                },
            },
            {
                id = 'removecoins',
                label = 'Remove coins',
                hint = '/removecoins [id] [amount]',
                command = 'removecoins {player} {amount}',
                fields = {
                    { name = 'player', type = 'player', label = 'Player' },
                    { name = 'amount', type = 'number', label = 'Amount', min = 1, max = 1000000, default = 100 },
                },
            },
            {
                id = 'setcoins',
                label = 'Set coins',
                hint = '/setcoins [id] [amount]',
                command = 'setcoins {player} {amount}',
                fields = {
                    { name = 'player', type = 'player', label = 'Player' },
                    { name = 'amount', type = 'number', label = 'Amount', min = 0, max = 1000000, default = 0 },
                },
            },
            {
                id = 'checkcoins',
                label = 'Check coins',
                hint = '/checkcoins [id]',
                command = 'checkcoins {player}',
                fields = {
                    { name = 'player', type = 'player', label = 'Player' },
                },
            },
        },
    },
    {
        id = 'shops',
        resource = 'djfivem-shops',
        label = 'Shops',
        tag = 'Retail',
        category = 'economy',
        icon = 'bag',
        description = 'Ped shops with cash / bank checkout and ox_inventory.',
        actions = {},
    },
    {
        id = 'blackmarket',
        resource = 'djfivem-blackmarket',
        label = 'Black Market',
        tag = 'Chiliad',
        category = 'economy',
        icon = 'skull',
        description = 'Mountain dealer, GPS vendor, weapons, and BM goods.',
        actions = {},
    },
    {
        id = 'drugs',
        resource = 'djfivem-drugs',
        label = 'Drugs',
        tag = 'Trap',
        category = 'crime',
        icon = 'flask',
        description = 'Harvest, process, and /trap street sales.',
        actions = {
            { id = 'trap', label = 'Toggle trap selling', hint = '/trap', command = 'trap' },
        },
    },
    {
        id = 'gambling',
        resource = 'djfivem_gambling',
        label = 'Gambling',
        tag = 'Tablet',
        category = 'entertainment',
        icon = 'dice',
        description = 'Black / red / white gambling tablet with configurable odds.',
        actions = {
            { id = 'open', label = 'Open gambling tablet', hint = '/gambling', command = 'gambling' },
        },
    },
    {
        id = 'fishing',
        resource = 'djfivem-fishing',
        label = 'Fishing',
        tag = 'Angler',
        category = 'jobs',
        icon = 'fish',
        description = 'Ocean, lake, and river fishing with tackle shop UI.',
        actions = {
            { id = 'fish', label = 'Start fishing', hint = '/fish', command = 'fish' },
            { id = 'kit', label = 'Give test fishing kit', hint = '/fishingkit', command = 'fishingkit' },
        },
    },
    {
        id = 'pets',
        resource = 'djfivem-pets',
        label = 'Pets',
        tag = 'Companions',
        category = 'cosmetics',
        icon = 'paw',
        description = 'Walkable GTA animals, needs, and pet menu.',
        actions = {
            { id = 'menu', label = 'Open pet menu', hint = '/petmenu', command = 'petmenu' },
            {
                id = 'givepet',
                label = 'Give pet item',
                hint = '/givepet [id] [species]',
                command = 'givepet {player} {species}',
                fields = {
                    { name = 'player', type = 'player', label = 'Player' },
                    {
                        name = 'species',
                        type = 'select',
                        label = 'Species',
                        options = {
                            'rottweiler', 'husky', 'retriever', 'shepherd', 'pug', 'poodle',
                            'cat', 'chop', 'rabbit', 'pig', 'coyote', 'monkey', 'mtlion',
                        },
                    },
                },
            },
        },
    },
    {
        id = 'wings',
        resource = 'djfivem-wings',
        label = 'Wings',
        tag = 'Wearables',
        category = 'cosmetics',
        icon = 'wing',
        description = 'Synced wing / shoulder props with live placement editor.',
        actions = {
            { id = 'editor', label = 'Open placement editor', hint = '/wingeditor', command = 'wingeditor' },
            { id = 'list', label = 'List wearables', hint = '/wings', command = 'wings' },
        },
    },
    {
        id = 'headcosmetics',
        resource = 'djfivem-headcosmetics',
        label = 'Head Cosmetics',
        tag = 'Crowns',
        category = 'cosmetics',
        icon = 'crown',
        description = 'Crowns, halos, and hug plushies with live adjust.',
        actions = {
            { id = 'adjust', label = 'Adjust cosmetic', hint = '/adjustcosmetic', command = 'adjustcosmetic' },
            { id = 'clear', label = 'Clear cosmetics', hint = '/clearcosmetics', command = 'clearcosmetics' },
        },
    },
    {
        id = 'backbling',
        resource = 'dj-backbling',
        label = 'Back Bling',
        tag = 'Melee',
        category = 'cosmetics',
        icon = 'sword',
        description = 'Synced melee weapons on your back.',
        actions = {
            { id = 'editor', label = 'Open backbling editor', hint = '/backbling', command = 'backbling' },
            { id = 'refresh', label = 'Refresh attachments', hint = '/backblingrefresh', command = 'backblingrefresh' },
        },
    },
    {
        id = 'spraypaint',
        resource = 'djfivem-spraypaint',
        label = 'Spray Paint',
        tag = 'Chameleon',
        category = 'vehicles',
        icon = 'spray',
        description = '82 chameleon sprays and donation paint remover.',
        actions = {},
    },
    {
        id = 'doorlock',
        resource = 'djfivem-doorlock',
        label = 'Doorlock',
        tag = 'Access',
        category = 'world',
        icon = 'lock',
        description = 'Job / player door locks with in-game creator.',
        actions = {
            { id = 'creator', label = 'Open doorlock creator', hint = '/doorlock', command = 'doorlock' },
        },
    },
    {
        id = 'stashcreator',
        resource = 'dj-stashcreator',
        label = 'Stash Creator',
        tag = 'Storage',
        category = 'world',
        icon = 'box',
        description = 'In-game ox_inventory stash creator with locks.',
        actions = {
            { id = 'open', label = 'Open stash creator', hint = '/stash', command = 'stash' },
        },
    },
    {
        id = 'gangmanagement',
        resource = 'djfivem-gangmanagement',
        label = 'Gang Management',
        tag = 'Crews',
        category = 'crime',
        icon = 'users',
        description = 'Gang stashes, money, ranks, and member tools.',
        actions = {
            { id = 'menu', label = 'Open gang menu', hint = '/gangmenu', command = 'gangmenu' },
            { id = 'place_shared', label = 'Place shared stash', hint = '/placestash shared', command = 'placestash shared' },
            { id = 'place_boss', label = 'Place boss stash', hint = '/placestash boss', command = 'placestash boss' },
            { id = 'place_personal', label = 'Place personal stash', hint = '/placestash personal', command = 'placestash personal' },
            { id = 'place_menu', label = 'Place gang menu', hint = '/placestash menu', command = 'placestash menu' },
            { id = 'remove', label = 'Remove nearest stash', hint = '/removestash', command = 'removestash' },
        },
    },
    {
        id = 'gangs',
        resource = 'gangs',
        label = 'Gangs / Territories',
        tag = 'Zones',
        category = 'crime',
        icon = 'map',
        description = 'Territory wars, organizations, bounties, and zone editor.',
        actions = {
            { id = 'menu', label = 'Open criminal tablet', hint = '/criminal', command = 'criminal' },
            { id = 'zones', label = 'Open zone editor', hint = '/zoneeditor', command = 'zoneeditor' },
            { id = 'createzone', label = 'Create zone (editor)', hint = '/criminal createzone', command = 'criminal createzone' },
        },
    },
    {
        id = 'robbery',
        resource = 'djfivem-robbery',
        label = 'Robbery',
        tag = 'Heists',
        category = 'crime',
        icon = 'mask',
        description = 'Banks, stores, ATMs, vehicles, money trucks, Ammunation.',
        actions = {
            { id = 'tablet', label = 'Open robbery tablet', hint = '/robberytab', command = 'robberytab' },
        },
    },
    {
        id = 'arena',
        resource = 'cursor_arena',
        label = 'Arena',
        tag = 'PvP',
        category = 'entertainment',
        icon = 'target',
        description = 'FFA, TDM, and ranked team PvP arena.',
        actions = {
            { id = 'open', label = 'Open arena', hint = '/arena', command = 'arena' },
        },
    },
    {
        id = 'dabpen',
        resource = 'djfivem-dabpen',
        label = 'Dab Pen',
        tag = 'Coming soon',
        category = 'cosmetics',
        icon = 'cloud',
        description = 'Placeholder — repo is empty.',
        actions = {},
    },
    {
        id = 'boostevents',
        resource = 'djfivem-boostevents',
        label = 'Boost Events',
        tag = 'Coming soon',
        category = 'events',
        icon = 'bolt',
        description = 'Placeholder — repo is empty.',
        actions = {},
    },
}

CatalogByResource = {}
for i = 1, #Catalog do
    local item = Catalog[i]
    CatalogByResource[item.resource] = item
    if type(item.alts) == 'table' then
        for a = 1, #item.alts do
            CatalogByResource[item.alts[a]] = item
        end
    end
end
